/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Buku;
import controller.bukuCont;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author asus
 */
public class Buku_View extends javax.swing.JFrame {

    /**
     * Creates new form Buku
     */
    public Buku_View() {
        initComponents();
        buttonDelBuku.setEnabled(false);
        buttonAddStock.setEnabled(false);
        Load();
        
    }
    public void Load() {
        bukuCont dao = new bukuCont();
        List<Buku> list = dao.list();
        String [] daftarlist  = new String[list.size()];
        int i = 0;
        while (i < list.size()) {
            daftarlist[i] = list.get(i).getJudul();
            i++;
        }
        listBuku.setListData(daftarlist);
        listBuku.addListSelectionListener(((ListSelectionEvent e) -> {
            buttonDelBuku.setEnabled(true);
            buttonAddStock.setEnabled(true);
            viewBuku.setText("ISBN \t   = " + list.get(listBuku.getSelectedIndex()).getISBN() + "\n" +
                             "Judul \t   = " + list.get(listBuku.getSelectedIndex()).getJudul() + "\n" +
                             "Penulis \t   = " + list.get(listBuku.getSelectedIndex()).getPenulis() + "\n" +
                             "Jenis Buku \t   = " + list.get(listBuku.getSelectedIndex()).getJenisBuku() + "\n" +
                             "Jumlah Halaman = " + list.get(listBuku.getSelectedIndex()).getJumlahHalaman() + "\n" +
                             "Stock \t    = " + list.get(listBuku.getSelectedIndex()).getStock()
            );
        }));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listBuku = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewBuku = new javax.swing.JTextArea();
        buttonAddBuku = new javax.swing.JButton();
        buttonDelBuku = new javax.swing.JButton();
        buttonBackBuku = new javax.swing.JButton();
        buttonAddStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listBuku);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("BUKU PERPUSTAKAAN");

        viewBuku.setEditable(false);
        viewBuku.setColumns(20);
        viewBuku.setRows(5);
        jScrollPane2.setViewportView(viewBuku);

        buttonAddBuku.setText("Tambah Buku");
        buttonAddBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddBukuActionPerformed(evt);
            }
        });

        buttonDelBuku.setText("Hapus");
        buttonDelBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelBukuActionPerformed(evt);
            }
        });

        buttonBackBuku.setText("Kembali");
        buttonBackBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackBukuActionPerformed(evt);
            }
        });

        buttonAddStock.setText("Tambah Stock");
        buttonAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAddStock, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(buttonAddBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDelBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonBackBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAddStock, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(buttonDelBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBackBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(buttonAddBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddBukuActionPerformed
        this.dispose();
        new TambahBuku().setVisible(true);
    }//GEN-LAST:event_buttonAddBukuActionPerformed

    private void buttonBackBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackBukuActionPerformed
        new menuLibrarian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackBukuActionPerformed

    private void buttonDelBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelBukuActionPerformed
        Buku buku = new Buku();
        buku.setJudul(listBuku.getSelectedValue());
        bukuCont bukucont = new bukuCont();
        bukucont.del(buku);
        this.dispose();
        new Buku_View().setVisible(true);
    }//GEN-LAST:event_buttonDelBukuActionPerformed

    private void buttonAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddStockActionPerformed
        int search = Integer.parseInt(JOptionPane.showInputDialog("Masukan nilai stock"));
        bukuCont bukucont = new bukuCont();
        Buku buku = bukucont.getStock(listBuku.getSelectedValue());
        buku.setStock(search+buku.getStock());
        bukucont.addStock(buku);
        new Buku_View().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAddStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddBuku;
    private javax.swing.JButton buttonAddStock;
    private javax.swing.JButton buttonBackBuku;
    private javax.swing.JButton buttonDelBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listBuku;
    private javax.swing.JTextArea viewBuku;
    // End of variables declaration//GEN-END:variables
}
